---
title: "First Example"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library("vegawidget")
library("magrittr")
library("tibble")
library("readr")
library("purrr")
```

Let's write a vega-lite spec!

Here's a JSON spec

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

```{r}
data_values <-
  list(
    list(a = "A", b = 28),
    list(a = "B", b = 55),
    list(a = "C", b = 43),
    list(a = "D", b = 91),
    list(a = "E", b = 81),
    list(a = "F", b = 53),
    list(a = "G", b = 19),
    list(a = "H", b = 87),
    list(a = "I", b = 52)
  )

spec <- 
  list(
    `$schema` = "https://vega.github.io/schema/vega-lite/v2.json",
    description = "A simple bar chart with embedded data.",
    data = list(values = data_values),
    mark = "bar",
    encoding = list(
      x = list(field = "a", type = "ordinal"),
      y = list(field = "b", type = "quantitative")
    )
  )

vegawidget::vegawidget(spec)
```

```{r}
spec_named <- 
  list(
    `$schema` = "https://vega.github.io/schema/vega-lite/v2.json",
    description = "A simple bar chart with embedded data.",
    datasets = 
      list(
        sample = data_values
      ),
    data = list(name = "sample"),
    mark = "bar",
    encoding = list(
      x = list(field = "a", type = "ordinal"),
      y = list(field = "b", type = "quantitative")
    )
  )

vegawidget::vegawidget(spec_named)
```

```{r}
data <- 
  tibble(
    a = c("A", "B", "C", "D", "E", "F", "G", "H", "I"),
    b = c(28, 55, 43, 91, 81, 53, 19, 87, 52)
  )

data_csv <-
  list(
    values = format_csv(data),
    format = list(
      type = "csv"   
    )
  )
```

```{r}
spec_csv <- spec

spec_csv$data <- data_csv

vegawidget::vegawidget(spec_csv)  
```

```{r}
spec_named_csv <- spec_named

spec_named_csv$datasets$sample <- csv
spec_named_csv$data <- list(
  name = "sample",
  format = list(type = "csv")
)

vegawidget::vegawidget(spec_named_csv)
```

Let's try to modify a spec that we create using a data-frame:

```{r}
spec_data_frame <- spec

spec_data_frame$data <- data

to_csv <- function(x) {
  list(
    values = readr::format_csv(x),
    format = list(
      type = "csv"   
    )
  )
}

wrap_recursive <- function(x) {
  
  if (is.data.frame(x)) {
    x_new <- to_csv(x)
  } else if (is.list(x)) {
    x_new <- map(x, wrap_recursive)
  } else {
    x_new <- x
  }
  
  x_new
}

spec_data_frame_new <- map(spec_data_frame, wrap_recursive)

vegawidget(spec_data_frame_new)
```

```{r}
spec_test <- 
  list(
    a = spec_data_frame,
    b = spec_data_frame
  )

spec_test_new <- map(spec_test, wrap_recursive)
```
